### PR TITLE
Use connections default sender instead of 'open_sender'

### PR DESCRIPTION
**Pull request by sedroche**
## Motivation
Jira: https://issues.jboss.org/browse/INTLY-968

## What
The `open_sender` function errors if the specified target does not exist. There is some error handling for AMQP errors but if the queue is not created quickly enough the pod health checks fail and the pod is down.

This change moves to using the connection object default sender which is a sending link whose target address is null.
The use of this method depends on the peer supporting so-called 'anonymous relay' semantics, which our AMQP does.
The message should have the 'to' field set to the intended target/destination.

https://www.npmjs.com/package/rhea#sendmessage

## Verification Steps
- Start Walkthrough 1A "Integrating message-oriented middleware with a RESTful API using AMQ Online" i.e. Select `Get Started` button and let the user namespace `<user> - 1A-integrate-event-and-api-driven-apps` be created.
- Wait. The pod for `nodejs-messaging-work-queue-frontend` should be bouncing and the deployment will eventually fail.
- Update the `nodejs-messaging-work-queue-frontend` deployment config to use `quay.io/sedroche/nodejs-messaging-work-queue:dynamic` which contains these changes.
- The pod should start correctly
- The walkthrough should be able to be completed e.g. message can be sent from the node app to the crud app (`NodeJS App -> AMQ Online -> Fuse Integration -> CRUD App`)

## Checklist:

- [x] Code has been tested locally by PR requester
- [ ] Changes have been successfully verified by another team member

### CODE REVIEW

**Comment by tremes** [comment]
I'll check today on my PDS. Thanks John

**Review by tremes — APPROVED** [review]
Works as expected

**Comment by tremes** [comment]
@aidenkeating @david-martin can one of you please check and possibly merge? I don't want to merge when there is only my review TBH.

**Comment by aidenkeating** [comment]
:eyes:

**Review by aidenkeating — APPROVED** [review]
Tried it out. Worked as expected based on the steps in the verification. We'll need to ensure a build of this gets on to quay and the template created in the installer references it.

**Pull request merged**
