### PR TITLE
INTLY-3036-CI Build

### PR DESCRIPTION
**Pull request by KevFan**
## Description
Merge the branch with master so that master (and any other branch based from master) would have the Dockerfile for automating builds and sync with the latest frontend changes

### CODE REVIEW

**Review by dimitraz — APPROVED** [review]
Looks good to me :+1:

**Review by aidenkeating — APPROVED** [review]
@KevFan Looks good.

Let's bump the version to `4.0.0` as a new start, merge and create a `4.0.0` tag on the repo.

I've created the build trigger in Quay already.

**Comment by aidenkeating** [comment]
@KevFan Let's also ensure we don't remove the `deploy_frontend_only` branch after we merge this. Until we are certain no documentation etc. references that branch

**Comment by KevFan** [comment]
@aidenkeating Cool thanks, will do, version have been bumped to 4.0.0. Going to merge if all is good

**Pull request merged**
